from app.extensions.init_sqlalchemy import db


# 财务审计意见
class Fina_audit(db.Model):
    __tablename__ = 'fina_audit'
    id = db.Column(db.Integer, primary_key=True, comment='财务审计意见编号')
    ts_code = db.Column(db.String(255), comment='TS股票代码')
    ann_date = db.Column(db.String(255), comment='公告日期')
    end_date = db.Column(db.String(255), comment='报告期')
    audit_result = db.Column(db.String(255), comment='审计结果')
    audit_fees = db.Column(db.Float, comment='审计总费用（元）')
    audit_agency = db.Column(db.String(255), comment='会计事务所')
    audit_sign = db.Column(db.String(255), comment='签字会计师')


# 资产负债表
class Balance(db.Model):
    __tablename__ = 'balance_sheet'
    id = db.Column(db.Integer, primary_key=True, comment='负债表编号')
    ts_code = db.Column(db.String(255), comment='TS股票代码')
    ann_date = db.Column(db.String(255), comment='公告日期')
    f_ann_date = db.Column(db.String(255), comment='实际公告日期')
    end_date = db.Column(db.String(255), comment='报告期')
    report_type = db.Column(db.String(255), comment='报表类型')
    comp_type = db.Column(db.String(255), comment='公司类型')
    total_share = db.Column(db.Float, comment='期末总股本')
    cap_rese = db.Column(db.Float, comment='资本公积金')
    undistr_porfit = db.Column(db.Float, comment='未分配利润')
    surplus_rese = db.Column(db.Float, comment='盈余公积金')
    special_rese = db.Column(db.Float, comment='专项储备')
    money_cap = db.Column(db.Float, comment='货币资金')
    trad_asset = db.Column(db.Float, comment='交易性金融资产')
    notes_receiv = db.Column(db.Float, comment='应收票据')
    accounts_receiv = db.Column(db.Float, comment='应收账款')
    oth_receiv = db.Column(db.Float, comment='其他应收款')
    prepayment = db.Column(db.Float, comment='预付款项')
    div_receiv = db.Column(db.Float, comment='应收股利')
    int_receiv = db.Column(db.Float, comment='应收利息')
    inventories = db.Column(db.Float, comment='存货')
    amor_exp = db.Column(db.Float, comment='待摊费用')
    nca_within_1y = db.Column(db.Float, comment='一年内到期的非流动资产')
    sett_rsrv = db.Column(db.Float, comment='结算备付金')
    loanto_oth_bank_fi = db.Column(db.Float, comment='拆出资金')
    premium_receiv = db.Column(db.Float, comment='应收保费')
    reinsur_receiv = db.Column(db.Float, comment='应收分保账款')
    reinsur_res_receiv = db.Column(db.Float, comment='应收分保合同准备金')
    pur_resale_fa = db.Column(db.Float, comment='买入返售金融资产')
    oth_cur_assets = db.Column(db.Float, comment='其他流动资产')
    total_cur_assets = db.Column(db.Float, comment='流动资产合计')
    fa_avail_for_sale = db.Column(db.Float, comment='可供出售金融资产')
    htm_invest = db.Column(db.Float, comment='持有至到期投资')
    lt_eqt_invest = db.Column(db.Float, comment='长期股权投资')
    invest_real_estate = db.Column(db.Float, comment='投资性房地产')
    time_deposits = db.Column(db.Float, comment='定期存款')
    oth_assets = db.Column(db.Float, comment='其他资产')
    lt_rec = db.Column(db.Float, comment='长期应收款')
    fix_assets = db.Column(db.Float, comment='固定资产')
    cip = db.Column(db.Float, comment='在建工程')
    const_materials = db.Column(db.Float, comment='工程物资')
    fixed_assets_disp = db.Column(db.Float, comment='固定资产清理')
    produc_bio_assets = db.Column(db.Float, comment='生产性生物资产')
    oil_and_gas_assets = db.Column(db.Float, comment='油气资产')
    intan_assets = db.Column(db.Float, comment='无形资产')
    r_and_d = db.Column(db.Float, comment='研发支出')
    goodwill = db.Column(db.Float, comment='商誉')
    lt_amor_exp = db.Column(db.Float, comment='长期待摊费用')
    defer_tax_assets = db.Column(db.Float, comment='递延所得税资产')
    decr_in_disbur = db.Column(db.Float, comment='发放贷款及垫款')
    oth_nca = db.Column(db.Float, comment='其他非流动资产')
    total_nca = db.Column(db.Float, comment='非流动资产合计')
    cash_reser_cb = db.Column(db.Float, comment='现金及存放中央银行款项')
    depos_in_oth_bfi = db.Column(db.Float, comment='存放同业和其它金融机构款项')
    prec_metals = db.Column(db.Float, comment='贵金属')
    deriv_assets = db.Column(db.Float, comment='	衍生金融资产')
    rr_reins_une_prem = db.Column(db.Float, comment='应收分保未到期责任准备金')
    rr_reins_outstd_cla = db.Column(db.Float, comment='应收分保未决赔款准备金')
    rr_reins_lins_liab = db.Column(db.Float, comment='应收分保寿险责任准备金')
    rr_reins_lthins_liab = db.Column(db.Float, comment='应收分保长期健康险责任准备金')
    refund_depos = db.Column(db.Float, comment='存出保证金')
    ph_pledge_loans = db.Column(db.Float, comment='保户质押贷款')
    refund_cap_depos = db.Column(db.Float, comment='存出资本保证金')
    indep_acct_assets = db.Column(db.Float, comment='独立账户资产')
    client_depos = db.Column(db.Float, comment='其中：客户资金存款')
    client_prov = db.Column(db.Float, comment='其中：客户备付金')
    transac_seat_fee = db.Column(db.Float, comment='其中:交易席位费')
    invest_as_receiv = db.Column(db.Float, comment='应收款项类投资')
    total_assets = db.Column(db.Float, comment='资产总计')
    lt_borr = db.Column(db.Float, comment='长期借款')
    st_borr = db.Column(db.Float, comment='短期借款')
    cb_borr = db.Column(db.Float, comment='向中央银行借款')
    depos_ib_deposits = db.Column(db.Float, comment='吸收存款及同业存放')
    loan_oth_bank = db.Column(db.Float, comment='拆入资金')
    trading_fl = db.Column(db.Float, comment='交易性金融负债')
    notes_payable = db.Column(db.Float, comment='应付票据')
    acct_payable = db.Column(db.Float, comment='应付账款')
    adv_receipts = db.Column(db.Float, comment='预收款项')
    sold_for_repur_fa = db.Column(db.Float, comment='卖出回购金融资产款')
    comm_payable = db.Column(db.Float, comment='应付手续费及佣金')
    payroll_payable = db.Column(db.Float, comment='应付职工薪酬')
    taxes_payable = db.Column(db.Float, comment='应交税费')
    int_payable = db.Column(db.Float, comment='应付利息')
    div_payable = db.Column(db.Float, comment='应付股利')
    oth_payable = db.Column(db.Float, comment='其他应付款')
    acc_exp = db.Column(db.Float, comment='预提费用')
    deferred_inc = db.Column(db.Float, comment='递延收益')
    st_bonds_payable = db.Column(db.Float, comment='应付短期债券')
    payable_to_reinsurer = db.Column(db.Float, comment='应付分保账款')
    rsrv_insur_cont = db.Column(db.Float, comment='保险合同准备金')
    acting_trading_sec = db.Column(db.Float, comment='代理买卖证券款')
    acting_uw_sec = db.Column(db.Float, comment='代理承销证券款')
    non_cur_liab_due_1y = db.Column(db.Float, comment='一年内到期的非流动负债')
    oth_cur_liab = db.Column(db.Float, comment='其他流动负债')
    total_cur_liab = db.Column(db.Float, comment='流动负债合计')
    bond_payable = db.Column(db.Float, comment='应付债券')
    lt_payable = db.Column(db.Float, comment='长期应付款')
    specific_payables = db.Column(db.Float, comment='专项应付款')
    estimated_liab = db.Column(db.Float, comment='预计负债')
    defer_tax_liab = db.Column(db.Float, comment='递延所得税负债')
    defer_inc_non_cur_liab = db.Column(db.Float, comment='递延收益-非流动负债')
    oth_ncl = db.Column(db.Float, comment='其他非流动负债')
    total_ncl = db.Column(db.Float, comment='非流动负债合计')
    depos_oth_bfi = db.Column(db.Float, comment='同业和其它金融机构存放款项')
    deriv_liab = db.Column(db.Float, comment='衍生金融负债')
    depos = db.Column(db.Float, comment='吸收存款')
    agency_bus_liab = db.Column(db.Float, comment='代理业务负债')
    oth_liab = db.Column(db.Float, comment='其他负债')
    prem_receiv_adva = db.Column(db.Float, comment='预收保费')
    depos_received = db.Column(db.Float, comment='存入保证金')
    ph_invest = db.Column(db.Float, comment='保户储金及投资款')
    reser_une_prem = db.Column(db.Float, comment='未到期责任准备金')
    reser_outstd_claims = db.Column(db.Float, comment='未决赔款准备金')
    reser_lins_liab = db.Column(db.Float, comment='寿险责任准备金')
    reser_lthins_liab = db.Column(db.Float, comment='长期健康险责任准备金')
    indept_acc_liab = db.Column(db.Float, comment='独立账户负债')
    pledge_borr = db.Column(db.Float, comment='其中:质押借款')
    indem_payable = db.Column(db.Float, comment='应付赔付款')
    policy_div_payable = db.Column(db.Float, comment='应付保单红利')
    total_liab = db.Column(db.Float, comment='负债合计')
    treasury_share = db.Column(db.Float, comment='减:库存股')
    ordin_risk_reser = db.Column(db.Float, comment='一般风险准备')
    forex_differ = db.Column(db.Float, comment='外币报表折算差额')
    invest_loss_unconf = db.Column(db.Float, comment='未确认的投资损失')
    minority_int = db.Column(db.Float, comment='少数股东权益')
    total_hldr_eqy_exc_min_int = db.Column(db.Float,
                                           comment='股东权益合计(不含少数股东权益)')
    total_hldr_eqy_inc_min_int = db.Column(db.Float, comment='股东权益合计(含少数股东权益)')
    total_liab_hldr_eqy = db.Column(db.Float, comment='负债及股东权益总计')
    lt_payroll_payable = db.Column(db.Float, comment='长期应付职工薪酬')
    oth_comp_income = db.Column(db.Float, comment='其他综合收益')
    oth_eqt_tools = db.Column(db.Float, comment='其他权益工具')
    oth_eqt_tools_p_shr = db.Column(db.Float, comment='其他权益工具(优先股)')
    lending_funds = db.Column(db.Float, comment='融出资金')
    acc_receivable = db.Column(db.Float, comment='应收款项')
    st_fin_payable = db.Column(db.Float, comment='应付短期融资款')
    payables = db.Column(db.Float, comment='应付款项')
    hfs_assets = db.Column(db.Float, comment='持有待售的资产')
    hfs_sales = db.Column(db.Float, comment='持有待售的负债')
    # update_flag= db.Column(db.String(255), comment='更新标识')


# 利润表
class Income(db.Model):
    __tablename__ = 'income_statement'
    id = db.Column(db.Integer, primary_key=True, comment='利润表编号')
    ts_code = db.Column(db.String(255), comment='TS股票代码')
    ann_date = db.Column(db.String(255), comment='公告日期')
    f_ann_date = db.Column(db.String(255), comment='实际公告日期')
    end_date = db.Column(db.String(255), comment='报告期')
    report_type = db.Column(db.String(255), comment='报表类型')
    comp_type = db.Column(db.String(255), comment='公司类型')
    end_type = db.Column(db.String(255), comment='报告期类型')
    basic_eps = db.Column(db.Float, comment='基本每股收益')
    diluted_eps = db.Column(db.Float, comment='稀释每股收益')
    total_revenue = db.Column(db.Float, comment='营业总收入')
    revenue = db.Column(db.Float, comment='营业收入')
    int_income = db.Column(db.Float, comment='利息收入')
    prem_earned = db.Column(db.Float, comment='已赚保费')
    comm_income = db.Column(db.Float, comment='手续费及佣金收入')
    n_commis_income = db.Column(db.Float, comment='手续费及佣金净收入')
    n_oth_income = db.Column(db.Float, comment='其他经营净收益')
    n_oth_b_income = db.Column(db.Float, comment='加:其他业务净收益')
    prem_income = db.Column(db.Float, comment='保险业务收入')
    out_prem = db.Column(db.Float, comment='减:分出保费')
    une_prem_reser = db.Column(db.Float, comment='提取未到期责任准备金')
    reins_income = db.Column(db.Float, comment='其中:分保费收入')
    n_sec_tb_income = db.Column(db.Float, comment='代理买卖证券业务净收入')
    n_sec_uw_income = db.Column(db.Float, comment='证券承销业务净收入')
    n_asset_mg_income = db.Column(db.Float, comment='受托客户资产管理业务净收入')
    oth_b_income = db.Column(db.Float, comment='其他业务收入')
    fv_value_chg_gain = db.Column(db.Float, comment='加:公允价值变动净收益')
    invest_income = db.Column(db.Float, comment='加:投资净收益')
    ass_invest_income = db.Column(db.Float, comment='其中:对联营企业和合营企业的投资收益')
    forex_gain = db.Column(db.Float, comment='加:汇兑净收益')
    total_cogs = db.Column(db.Float, comment='营业总成本')
    oper_cost = db.Column(db.Float, comment='减:营业成本')
    int_exp = db.Column(db.Float, comment='减:利息支出')
    comm_exp = db.Column(db.Float, comment='减:手续费及佣金支出')
    biz_tax_surchg = db.Column(db.Float, comment='减:营业税金及附加')
    sell_exp = db.Column(db.Float, comment='减:销售费用')
    admin_exp = db.Column(db.Float, comment='减:管理费用')
    fin_exp = db.Column(db.Float, comment='减:财务费用')
    assets_impair_loss = db.Column(db.Float, comment='减:资产减值损失')
    prem_refund = db.Column(db.Float, comment='退保金')
    compens_payout = db.Column(db.Float, comment='赔付总支出')
    reser_insur_liab = db.Column(db.Float, comment='提取保险责任准备金')
    div_payt = db.Column(db.Float, comment='保户红利支出')
    reins_exp = db.Column(db.Float, comment='分保费用')
    oper_exp = db.Column(db.Float, comment='营业支出')
    compens_payout_refu = db.Column(db.Float, comment='减:摊回赔付支出')
    insur_reser_refu = db.Column(db.Float, comment='减:摊回保险责任准备金')
    reins_cost_refund = db.Column(db.Float, comment='减:摊回分保费用')
    other_bus_cost = db.Column(db.Float, comment='其他业务成本')
    operate_profit = db.Column(db.Float, comment='营业利润')
    non_oper_income = db.Column(db.Float, comment='加:营业外收入')
    non_oper_exp = db.Column(db.Float, comment='减:营业外支出')
    nca_disploss = db.Column(db.Float, comment='其中:减:非流动资产处置净损失')
    total_profit = db.Column(db.Float, comment='利润总额')
    income_tax = db.Column(db.Float, comment='所得税费用')
    n_income = db.Column(db.Float, comment='净利润(含少数股东损益)')
    n_income_attr_p = db.Column(db.Float, comment='净利润(不含少数股东损益)')
    minority_gain = db.Column(db.Float, comment='少数股东损益')
    oth_compr_income = db.Column(db.Float, comment='其他综合收益')
    t_compr_income = db.Column(db.Float, comment='综合收益总额')
    compr_inc_attr_p = db.Column(db.Float, comment='归属于母公司(或股东)的综合收益总额')
    compr_inc_attr_m_s = db.Column(db.Float, comment='归属于少数股东的综合收益总额')
    ebit = db.Column(db.Float, comment='息税前利润')
    ebitda = db.Column(db.Float, comment='息税折旧摊销前利润')
    insurance_exp = db.Column(db.Float, comment='保险业务支出')
    undist_profit = db.Column(db.Float, comment='年初未分配利润')
    distable_profit = db.Column(db.Float, comment='	可分配利润')
    rd_exp = db.Column(db.Float, comment='研发费用')
    fin_exp_int_exp = db.Column(db.Float, comment='财务费用:利息费用')
    fin_exp_int_inc = db.Column(db.Float, comment='财务费用:利息收入')
    transfer_surplus_rese = db.Column(db.Float, comment='盈余公积转入')
    transfer_housing_imprest = db.Column(db.Float, comment='住房周转金转入')
    transfer_oth = db.Column(db.Float, comment='其他转入')
    adj_lossgain = db.Column(db.Float, comment='调整以前年度损益')
    withdra_legal_surplus = db.Column(db.Float, comment='提取法定盈余公积')
    withdra_legal_pubfund = db.Column(db.Float, comment='提取法定公益金')
    withdra_biz_devfund = db.Column(db.Float, comment='提取企业发展基金')
    withdra_rese_fund = db.Column(db.Float, comment='提取储备基金')
    withdra_oth_ersu = db.Column(db.Float, comment='提取任意盈余公积金')
    workers_welfare = db.Column(db.Float, comment='职工奖金福利')
    distr_profit_shrhder = db.Column(db.Float, comment='可供股东分配的利润')
    prfshare_payable_dvd = db.Column(db.Float, comment='应付优先股股利')
    comshare_payable_dvd = db.Column(db.Float, comment='应付普通股股利')
    capit_comstock_div = db.Column(db.Float, comment='转作股本的普通股股利')
    net_after_nr_lp_correct = db.Column(db.Float, comment='扣除非经常性损益后的净利润（更正前）')
    credit_impa_loss = db.Column(db.Float, comment='信用减值损失')
    net_expo_hedging_benefits = db.Column(db.Float, comment='净敞口套期收益')
    oth_impair_loss_assets = db.Column(db.Float, comment='其他资产减值损失')
    total_opcost = db.Column(db.Float, comment='营业总成本（二）')
    amodcost_fin_assets = db.Column(db.Float, comment='以摊余成本计量的金融资产终止确认收益')
    oth_income = db.Column(db.Float, comment='其他收益')
    asset_disp_income = db.Column(db.Float, comment='资产处置收益')
    continued_net_profit = db.Column(db.Float, comment='持续经营净利润')
    end_net_profit = db.Column(db.Float, comment='终止经营净利润')
    update_flag = db.Column(db.Float, comment='	更新标识')


# 现金流量表
class Cashflow(db.Model):
    __tablename__ = 'cash_flow'
    id = db.Column(db.Integer, primary_key=True, comment='现金流量表编号')
    ts_code = db.Column(db.String(255), comment='TS股票代码')
    ann_date = db.Column(db.String(255), comment='公告日期')
    f_ann_date = db.Column(db.String(255), comment='实际公告日期')
    end_date = db.Column(db.String(255), comment='报告期')
    report_type = db.Column(db.String(255), comment='报表类型')
    end_type = db.Column(db.String(255), comment='报告期类型')
    net_profit = db.Column(db.Float, comment='净利润')
    finan_exp = db.Column(db.Float, comment='财务费用')
    c_fr_sale_sg = db.Column(db.Float, comment='销售商品、提供劳务收到的现金')
    recp_tax_rends = db.Column(db.Float, comment='收到的税费返还')
    n_depos_incr_fi = db.Column(db.Float, comment='客户存款和同业存放款项净增加额')
    n_incr_loans_cb = db.Column(db.Float, comment='向中央银行借款净增加额')
    n_inc_borr_oth_fi = db.Column(db.Float, comment='向其他金融机构拆入资金净增加额')
    prem_fr_orig_contr = db.Column(db.Float, comment='收到原保险合同保费取得的现金')
    n_incr_insured_dep = db.Column(db.Float, comment='保户储金净增加额')
    n_reinsur_prem = db.Column(db.Float, comment='收到再保业务现金净额')
    n_incr_disp_tfa = db.Column(db.Float, comment='处置交易性金融资产净增加额')
    ifc_cash_incr = db.Column(db.Float, comment='收取利息和手续费净增加额')
    n_incr_disp_faas = db.Column(db.Float, comment='处置可供出售金融资产净增加额')
    n_incr_loans_oth_bank = db.Column(db.Float, comment='拆入资金净增加额')
    n_cap_incr_repur = db.Column(db.Float, comment='回购业务资金净增加额')
    c_fr_oth_operate_a = db.Column(db.Float, comment='收到其他与经营活动有关的现金')
    c_inf_fr_operate_a = db.Column(db.Float, comment='经营活动现金流入小计')
    c_paid_goods_s = db.Column(db.Float, comment='购买商品、接受劳务支付的现金')
    c_paid_to_for_empl = db.Column(db.Float, comment='支付给职工以及为职工支付的现金')
    c_paid_for_taxes = db.Column(db.Float, comment='支付的各项税费')
    n_incr_clt_loan_adv = db.Column(db.Float, comment='客户贷款及垫款净增加额')
    n_incr_dep_cbob = db.Column(db.Float, comment='存放央行和同业款项净增加额')
    c_pay_claims_orig_inco = db.Column(db.Float, comment='支付原保险合同赔付款项的现金')
    pay_handling_chrg = db.Column(db.Float, comment='支付手续费的现金')
    pay_comm_insur_plcy = db.Column(db.Float, comment='支付保单红利的现金')
    oth_cash_pay_oper_act = db.Column(db.Float, comment='支付其他与经营活动有关的现金')
    st_cash_out_act = db.Column(db.Float, comment='经营活动现金流出小计')
    n_cashflow_act = db.Column(db.Float, comment='经营活动产生的现金流量净额')
    oth_recp_ral_inv_act = db.Column(db.Float, comment='收到其他与投资活动有关的现金')
    c_disp_withdrwl_invest = db.Column(db.Float, comment='收回投资收到的现金')
    c_recp_return_invest = db.Column(db.Float, comment='取得投资收益收到的现金')
    n_recp_disp_fiolta = db.Column(db.Float,
                                   comment='处置固定资产、无形资产和其他长期资产收回的现金净额')
    n_recp_disp_sobu = db.Column(db.Float, comment='处置子公司及其他营业单位收到的现金净额')
    stot_inflows_inv_act = db.Column(db.Float, comment='投资活动现金流入小计')
    c_pay_acq_const_fiolta = db.Column(db.Float,
                                       comment='购建固定资产、无形资产和其他长期资产支付的现金')
    c_paid_invest = db.Column(db.Float, comment='投资支付的现金')
    n_disp_subs_oth_biz = db.Column(db.Float, comment='取得子公司及其他营业单位支付的现金净额')
    oth_pay_ral_inv_act = db.Column(db.Float, comment='支付其他与投资活动有关的现金')
    n_incr_pledge_loan = db.Column(db.Float, comment='质押贷款净增加额')
    stot_out_inv_act = db.Column(db.Float, comment='投资活动现金流出小计')
    n_cashflow_inv_act = db.Column(db.Float, comment='投资活动产生的现金流量净额')
    c_recp_borrow = db.Column(db.Float, comment='取得借款收到的现金')
    proc_issue_bonds = db.Column(db.Float, comment='发行债券收到的现金')
    oth_cash_recp_ral_fnc_act = db.Column(db.Float, comment='收到其他与筹资活动有关的现金')
    stot_cash_in_fnc_act = db.Column(db.Float, comment='筹资活动现金流入小计')
    free_cashflow = db.Column(db.Float, comment='企业自由现金流量')
    c_prepay_amt_borr = db.Column(db.Float, comment='偿还债务支付的现金')
    c_pay_dist_dpcp_int_exp = db.Column(db.Float, comment='分配股利、利润或偿付利息支付的现金')
    incl_dvd_profit_paid_sc_ms = db.Column(db.Float,
                                           comment='其中:子公司支付给少数股东的股利、利润')
    oth_cashpay_ral_fnc_act = db.Column(db.Float, comment='支付其他与筹资活动有关的现金')
    stot_cashout_fnc_act = db.Column(db.Float, comment='筹资活动现金流出小计')
    n_cash_flows_fnc_act = db.Column(db.Float, comment='筹资活动产生的现金流量净额')
    eff_fx_flu_cash = db.Column(db.Float, comment='汇率变动对现金的影响')
    n_incr_cash_cash_equ = db.Column(db.Float, comment='现金及现金等价物净增加额')
    c_cash_equ_beg_period = db.Column(db.Float, comment='期初现金及现金等价物余额')
    c_cash_equ_end_period = db.Column(db.Float, comment='期末现金及现金等价物余额')
    c_recp_cap_contrib = db.Column(db.Float, comment='吸收投资收到的现金')
    incl_cash_rec_saims = db.Column(db.Float, comment='其中:子公司吸收少数股东投资收到的现金')
    uncon_invest_loss = db.Column(db.Float, comment='未确认投资损失')
    prov_depr_assets = db.Column(db.Float, comment='加:资产减值准备')
    depr_fa_coga_dpba = db.Column(db.Float, comment='固定资产折旧、油气资产折耗、生产性生物资产折旧')
    amort_intang_assets = db.Column(db.Float, comment='无形资产摊销')
    lt_amort_deferred_exp = db.Column(db.Float, comment='长期待摊费用摊销')
    decr_deferred_exp = db.Column(db.Float, comment='待摊费用减少')
    incr_acc_exp = db.Column(db.Float, comment='预提费用增加')
    loss_disp_fiolta = db.Column(db.Float, comment='处置固定、无形资产和其他长期资产的损失')
    loss_scr_fa = db.Column(db.Float, comment='固定资产报废损失')
    loss_fv_chg = db.Column(db.Float, comment='公允价值变动损失')
    invest_loss = db.Column(db.Float, comment='投资损失')
    decr_def_inc_tax_assets = db.Column(db.Float, comment='递延所得税资产减少')
    incr_def_inc_tax_liab = db.Column(db.Float, comment='递延所得税负债增加')
    decr_inventories = db.Column(db.Float, comment='存货的减少')
    decr_oper_payable = db.Column(db.Float, comment='经营性应收项目的减少')
    incr_oper_payable = db.Column(db.Float, comment='经营性应付项目的增加')
    others = db.Column(db.Float, comment='其他')
    im_net_cashflow_oper_act = db.Column(db.Float,
                                         comment='经营活动产生的现金流量净额(间接法)')
    conv_debt_into_cap = db.Column(db.Float, comment='债务转为资本')
    conv_copbonds_due_within_1y = db.Column(db.Float, comment='一年内到期的可转换公司债券')
    fa_fnc_leases = db.Column(db.Float, comment='融资租入固定资产')
    im_n_incr_cash_equ = db.Column(db.Float, comment='现金及现金等价物净增加额(间接法)')
    net_dism_capital_add = db.Column(db.Float, comment='拆出资金净增加额')
    net_cash_rece_sec = db.Column(db.Float, comment='代理买卖证券收到的现金净额(元)')
    credit_impa_loss = db.Column(db.Float, comment='信用减值损失')
    use_right_asset_dep = db.Column(db.Float, comment='使用权资产折旧')
    oth_loss_asset = db.Column(db.Float, comment='其他资产减值损失')
    end_bal_cash = db.Column(db.Float, comment='现金的期末余额')
    beg_bal_cash = db.Column(db.Float, comment='减:现金的期初余额')
    end_bal_cash_equ = db.Column(db.Float, comment='加:现金等价物的期末余额')
    beg_bal_cash_equ = db.Column(db.Float, comment='减:现金等价物的期初余额')
    update_flag = db.Column(db.Float, comment='更新标志(1最新）')